[workspace]
members = [
    "zarza-daemon",
    "zarza-wallet",
    "zarza-miner",
    "zarza-consensus",
    "zarza-network",
    "zrzhash"
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
